version: '3.8'

networks:
  main:
  logs:
    external: true

services:
  backend:
    build: .
    ports:
      - "127.0.0.1:7891:3001"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:3001
    volumes:
      - ./logs/backend:/app/logs
      - ./keys:/root/.aspnet/DataProtection-Keys
    networks:
      - main
      - logs